---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-with-condition
  annotations:
    render.crossplane.io/runtime: Development
spec:
  package: xpkg.upbound.io/linuxarpan/functions-template-go:v0.11.0
...
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-patch-and-transform
  annotations:
    render.crossplane.io/runtime: Docker
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.2.1